name: library CI
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v4
                with:
                    java-version: '8'
                    distribution: 'temurin'

            -   name: Permission denied solve
                run: chmod +x ./maskit/gradlew

            -   name: Run tests
                run: cd maskit && ./gradlew clean test

    publish:
        runs-on: ubuntu-latest
        needs: test
        if: github.ref == 'refs/heads/main'

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v4
                with:
                    java-version: '8'
                    distribution: 'temurin'


            -   name: Get version from build.gradle
                id: get_version
                run: |
                    VERSION=$(grep -Eo "version = '[^']+'" ./maskit/build.gradle | awk -F"'" '{print $2}')
                    echo "Version extracted: $VERSION"
                    echo "::set-output name=version::$VERSION"

            - name: Set up Git automate user
              run: |
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"

            -   name: Tag the commit
                run: |
                    git tag -a "${{ steps.get_version.outputs.version }}" -m "Release version  ${{ steps.get_version.outputs.version }}"
                    git push origin "${{ steps.get_version.outputs.version }}"
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Read release notes
                id: read_release_notes
                run: |
                    TAG_NAME= ${{ steps.get_version.outputs.version }}
                    cat updates/${TAG_NAME}.md > release_notes.txt
                    echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
                    echo "릴리스 버전: ${TAG_NAME}" >> release_notes.txt
                    echo "릴리스 일시: ${RELEASE_DATE}" >> release_notes.txt
                    cat release_notes.txt >> $GITHUB_ENV
                    echo "EOF" >> $GITHUB_ENV

            -   name: Create a GitHub Release
                uses: softprops/action-gh-release@v1
                with:
                    tag_name: ${{ steps.get_version.outputs.version }}
                    release_name: Release  ${{ steps.get_version.outputs.version }}
                    body: ${{ env.RELEASE_NOTES }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   name: Permission denied solve
                run: chmod +x ./maskit/gradlew

            -   name: Build with Gradle
                run: cd maskit && ./gradlew build -x test

            -   name: Publish to local Maven repository
                run: cd maskit && ./gradlew publishToMavenLocal
