# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: library CI
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v2
                with:
                    java-version: '1.8'
                    distribution: 'adopt-openjdk'

            -   name: Build with Gradle
                run: ./gradlew build

            -   name: Run tests
                run: ./gradlew test

    publish:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/main'

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up JDK 1.8
                uses: actions/setup-java@v2
                with:
                    java-version: '1.8'
                    distribution: 'corretto'

            -   name: Build with Gradle
                run: ./gradlew build

            -   name: Run tests
                run: ./gradlew test

            -   name: Trigger JitPack build
                run: |
                    curl -X POST https://jitpack.io/api/builds \
                    -d "repo=${{ github.repository }}" \
                    -d "branch=main"
                env:
                    JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}